#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
---
apiVersion: v1
kind: Template
metadata:
  name: che-workspace-service-account
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_ACCOUNT_NAME}
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
- apiVersion: v1
  kind: Role
  metadata:
    name: exec
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
      - pods/exec
    verbs:
      - create
- apiVersion: v1
  kind: Role
  metadata:
    name: workspace-view
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods
    - services
    verbs:
    - list
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: che-workspace-exec
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  roleRef:
    name: exec
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: ${SERVICE_ACCOUNT_NAME}
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: che-workspace-view
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  roleRef:
    name: workspace-view
    namespace: ${SERVICE_ACCOUNT_NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: ${SERVICE_ACCOUNT_NAME}
parameters:
- name: SERVICE_ACCOUNT_NAME
  value: che-workspace
  displayName: Eclipse Che plugin registry image
  description: Service Account name that should be bound to workspaces. Defaults to 'che-workspace'
- name: SERVICE_ACCOUNT_NAMESPACE
  displayName: Service account namespace
  description: Namespace where service account should be created
  required: true
labels:
  app: che
  component: che
  template: che-workspace-service-account
