#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if and (eq .Values.global.serverStrategy "single-host") (eq .Values.global.singleHostExposure "gateway") }}

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
    component: che-gateway-config
  name: che-gateway-route-devfile-registry
data:
  devfile-registry.yml: |
    http:
      routers:
        devfile-registry:
          rule: "PathPrefix(`/devfile-registry`)"
          service: devfile-registry
          middlewares: [devfile-registry]
          priority: 10
      services:
        devfile-registry:
          loadBalancer:
            servers:
            - url: 'http://devfile-registry:8080'
      middlewares:
        devfile-registry:
          stripPrefix:
            prefixes:
            - '/devfile-registry'

{{- end }}
