kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: ws-name
spec:
  started: true
  template:
    projects:
      - name: project-name
        git:
          remotes:
            origin: git-repo-url
  contributions:
    - name: che-code
      uri: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/latest/devfile.yaml
      components:
        - name: che-code-runtime-description
          container:
            env:
              - name: CODE_HOST
                value: 0.0.0.0
