kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-secret
  namespace: eclipse-che
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: git-provider-url
type: Opaque
stringData:
  id: application-id
  secret: application-secret
