kind: Secret
apiVersion: v1
metadata:
  name: personal-access-token
  labels:
    app.kubernetes.io/component: scm-personal-access-token
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/che-userid: che-user-id
    che.eclipse.org/scm-personal-access-token-name: git-provider-name
    che.eclipse.org/scm-url: git-provider-url
    che.eclipse.org/scm-organization: ''
stringData:
  token: content-access-token
type: Opaque
