apiVersion: v1
kind: Pod
metadata:
  name: che-smoke-test
  namespace: CHE-NAMESPACE
spec:
  volumes:
    - name: test-run-results
    - name: ffmpeg-video
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    # container containing the tests
    - name: test
      image: quay.io/eclipse/che-e2e:next
      imagePullPolicy: Always
      env:
        - name: VIDEO_RECORDING
          value: "true"
        - name: TEST_SUITE
          value: "test"
        - name: TS_SELENIUM_EDITOR
          value: "che-code"
        - name: USERSTORY
          value: "SmokeTest"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: TS_SELENIUM_BASE_URL
          value: "CHE_URL"
        - name: TS_SELENIUM_LOG_LEVEL
          value: "TRACE"
        - name: TS_SELENIUM_OCP_USERNAME
          value: "OCP_USER_NAME"
        - name: TS_SELENIUM_OCP_PASSWORD
          value: "OCP_USER_PASSWORD"
        - name: TS_SELENIUM_VALUE_OPENSHIFT_OAUTH
          value: "true"
        - name: TS_OCP_LOGIN_PAGE_PROVIDER_TITLE
          value: "htpasswd"
        - name: DELETE_WORKSPACE_ON_FAILED_TEST
          value: "true"
        - name: TS_SELENIUM_START_WORKSPACE_TIMEOUT
          value: "360000"
        - name: TS_IDE_LOAD_TIMEOUT
          value: "40000"
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
        - name: ffmpeg-video
          mountPath: /tmp/ffmpeg_report/
        - name: dshm
          mountPath: /dev/shm
      resources:
        requests:
          memory: "3Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
    # Download results
    - name: download-reports
      image: eeacms/rsync
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
        - name: ffmpeg-video
          mountPath: /tmp/ffmpeg_report/
      resources:
      command: ["sh"]
      args:
        [
          "-c",
          "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done",
        ]
  restartPolicy: Never
