#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
{{- define "jaegerHost" }}
{{- printf "jaeger-%s.%s" .Release.Namespace .Values.global.ingressDomain }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query
  labels:
    app: jaeger
    jaeger-infra: jaeger-deployment
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | quote }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout: "3600"
{{- if .Values.global.tls.enabled }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "jaegerHost" . }}
    {{- if .Values.global.tls.secretName }}
    secretName: {{ .Values.global.tls.secretName }}
    {{- end -}}
{{- end }}
  rules:
  - host: {{ template "jaegerHost" . }}
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
