#
# Copyright (c) 2012-2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
    component: che
  name: che
data:
  CHE_HOST: {{ template "cheHost" . }}
  CHE_PORT: "8080"
{{- if and .Values.global.tls .Values.global.tls.enabled }}
  CHE_API: https://{{ template "cheHost" . }}/api
  {{- if .Values.global.useInternalClusterSVCNames }}
  CHE_API_INTERNAL: http://che-host.{{ .Release.Namespace }}.svc:8080/api
  {{- end }}
  CHE_WEBSOCKET_ENDPOINT:  wss://{{ template "cheHost" . }}/api/websocket
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: https://{{ template "cheHost" . }}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
{{ else }}
  CHE_API: http://{{ template "cheHost" . }}/api
  {{- if .Values.global.useInternalClusterSVCNames }}
  CHE_API_INTERNAL: http://che-host.{{ .Release.Namespace }}.svc:8080/api
  {{- end }}
  CHE_WEBSOCKET_ENDPOINT:  ws://{{ template "cheHost" . }}/api/websocket
  CHE_WEBSOCKET_ENDPOINT__MINOR:  ws://{{ template "cheHost" . }}/api/websocket-minor
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: http://{{ template "cheHost" . }}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
{{- end }}
{{- if .Values.global.useInternalClusterSVCNames }}
  CHE_WEBSOCKET_INTERNAL_ENDPOINT: ws://che-host.{{ .Release.Namespace }}.svc:8080/api/websocket
  CHE_WEBSOCKET_INTERNAL_ENDPOINT__MINOR: ws://che-host.{{ .Release.Namespace }}.svc:8080/api/websocket-minor
{{- end }}
  CHE_DEBUG_SERVER: "true"
  CHE_INFRASTRUCTURE_ACTIVE: "kubernetes"
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: {{ .Values.global.ingressDomain }}
  CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_MASTER__URL: ""
{{- if and .Values.global.tls .Values.global.tls.enabled }}
  CHE_INFRA_KUBERNETES_TLS__ENABLED: {{ .Values.global.tls.enabled | quote}}
  CHE_INFRA_KUBERNETES_TLS__SECRET: {{ .Values.global.tls.secretName | quote}}
{{- else }}
  CHE_INFRA_KUBERNETES_TLS__ENABLED: "false"
  CHE_INFRA_KUBERNETES_TLS__SECRET: ""
{{- end }}
  CHE_KEYCLOAK_CLIENT__ID: {{ .Values.cheKeycloakClientId | quote}}
  CHE_KEYCLOAK_AUTH__SERVER__URL: {{ template "keycloakAuthUrl" . }}
  {{- if .Values.global.useInternalClusterSVCNames }}
  CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL: http://keycloak.{{ .Release.Namespace }}.svc:5050/auth
  {{- end }}
  CHE_KEYCLOAK_REALM: {{ .Values.cheKeycloakRealm }}
{{- if .Values.customOidcProvider }}
  CHE_KEYCLOAK_OIDC__PROVIDER: {{ .Values.customOidcProvider }}
{{- end }}
{{- if .Values.customOidcUsernameClaim }}
  CHE_KEYCLOAK_USERNAME__CLAIM: {{ .Values.customOidcUsernameClaim }}
{{- end }}
{{- if not (eq .Values.global.tls.serverTrustStoreConfigMapName "") }}
  CHE_TRUSTED__CA__BUNDLES__CONFIGMAP: {{ .Values.global.tls.serverTrustStoreConfigMapName }}
{{- end }}
  # This is only kept for the upgrade purposes where we need to make sure we don't loose this piece of old configuration
  # so that we can find the data of old workspaces
  CHE_INFRA_KUBERNETES_NAMESPACE: {{ .Values.global.cheWorkspacesNamespace | quote}}
  CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: {{ .Values.global.cheWorkspacesNamespace | quote}}
  CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME: {{ .Values.global.cheWorkspaceServiceAccount }}
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "false"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "{{ .Values.global.cheWorkspacesPVCStrategy }}"
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: {{ .Values.global.pvcClaim }}
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "true"
  CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME: "{{ .Values.global.cheWorkspacePVCStorageClassName }}"
{{- if .Values.cheInfraKubernetesPvcJobsImage }}
  CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE: {{ .Values.cheInfraKubernetesPvcJobsImage | quote }}
{{- end }}
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "{{ .Values.global.securityContext.runAsUser }}"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "{{ .Values.global.securityContext.fsGroup }}"
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOGS_DIR: /data/logs
  CHE_LOG_LEVEL: {{ .Values.che.logLevel | quote }}
  CHE_MULTIUSER: "true"
  CHE_OAUTH_GITHUB_CLIENTID: {{ .Values.global.gitHubClientID | quote}}
  CHE_OAUTH_GITHUB_CLIENTSECRET: {{ .Values.global.gitHubClientSecret | quote}}
  CHE_OAUTH_OPENSHIFT_CLIENTID: {{ .Values.global.openShiftClientID | quote}}
  CHE_OAUTH_OPENSHIFT_CLIENTSECRET: {{ .Values.global.openShiftClientSecret | quote}}
  CHE_OAUTH_OPENSHIFT_OAUTH__ENDPOINT: {{ .Values.global.openShiftOAuthEndpoint | quote}}
  CHE_OAUTH_OPENSHIFT_VERIFY__TOKEN__URL: {{ .Values.global.openShiftVerifyTokenUrl | quote}}
  JAVA_OPTS: "-XX:MaxRAMPercentage=85.0 "
  CHE_WORKSPACE_AUTO_START: "false"
{{- if .Values.global.tls.enabled }}
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": {{ .Values.global.ingress.class | quote }}, "kubernetes.io/tls-acme": "true", "{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target": "/$1","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect": "true","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout": "3600","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout": "3600", "nginx.org/websocket-services": "<service-name>"}'
{{- else }}
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": {{ .Values.global.ingress.class | quote }}, "{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target": "/$1","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect": "false","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout": "3600","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout": "3600", "nginx.org/websocket-services": "<service-name>"}'
{{- end }}
  CHE_INFRA_KUBERNETES_INGRESS_PATH__TRANSFORM: '%s(.*)'
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: {{ .Values.global.serverStrategy }}
  CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE: {{ .Values.global.singleHostExposure | quote }}
  CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS: {{ .Values.global.singleHostGatewayLabels | quote }}
  CHE_LOGGER_CONFIG: {{ .Values.global.log.loggerConfig | quote}}
  CHE_LOGS_APPENDERS_IMPL: {{ .Values.global.log.appenderName }}
  CHE_WORKSPACE_HTTP__PROXY: {{ .Values.cheWorkspaceHttpProxy | quote}}
  CHE_WORKSPACE_HTTPS__PROXY: {{ .Values.cheWorkspaceHttpsProxy | quote}}
  CHE_WORKSPACE_NO__PROXY: {{ .Values.cheWorkspaceNoProxy | quote}}
  CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '{{ .Values.global.workspaceIdleTimeout }}'
{{- if .Values.che.limits.userWorkspacesRunCount }}
  CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: {{ .Values.che.limits.userWorkspacesRunCount | quote }}
{{- end }}
{{- if .Values.workspaceDefaultRamRequest }}
  CHE_WORKSPACE_DEFAULT_MEMORY_REQUEST_MB: {{ .Values.workspaceDefaultRamRequest | quote }}
{{- end }}
{{- if .Values.workspaceDefaultRamLimit }}
  CHE_WORKSPACE_DEFAULT_MEMORY_LIMIT_MB: {{ .Values.workspaceDefaultRamLimit | quote }}
{{- end }}
{{- if .Values.che.workspace.devfileRegistryUrl }}
  CHE_WORKSPACE_DEVFILE__REGISTRY__URL: {{ .Values.che.workspace.devfileRegistryUrl | quote }}
{{- else if .Values.cheDevfileRegistry.deploy }}
  CHE_WORKSPACE_DEVFILE__REGISTRY__URL: {{ template "devfileRegistryUrl" . }}
  {{- if .Values.global.useInternalClusterSVCNames }}
  CHE_WORKSPACE_DEVFILE__REGISTRY__INTERNAL__URL: http://devfile-registry.{{ .Release.Namespace }}.svc:8080
  {{- end }}
{{- end }}
{{- if .Values.che.workspace.pluginRegistryUrl }}
  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: {{ .Values.che.workspace.pluginRegistryUrl | quote }}
{{- else if .Values.chePluginRegistry.deploy }}
  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: {{ template "pluginRegistryUrl" . }}
  {{- if .Values.global.useInternalClusterSVCNames }}
  CHE_WORKSPACE_PLUGIN__REGISTRY__INTERNAL__URL: http://plugin-registry.{{ .Release.Namespace }}.svc:8080/v3
  {{- end }}
{{- end }}
{{- if .Values.che.workspace.pluginBroker }}
  {{- if .Values.che.workspace.pluginBroker.waitTimeoutMin }}
  CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: {{ .Values.che.workspace.pluginBroker.waitTimeoutMin | quote }}
  {{- end }}
  CHE_WORKSPACE_PLUGIN__BROKER_METADATA_IMAGE: {{ .Values.che.workspace.pluginBroker.metadataImage | quote }}
  CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE: {{ .Values.che.workspace.pluginBroker.artifactsImage | quote }}
{{- end }}
{{- if .Values.workspaceSidecarDefaultRamLimit }}
  CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB: {{ .Values.workspaceSidecarDefaultRamLimit | quote }}
{{- end }}
{{- if .Values.global.cheWorkspaceClusterRole }}
  CHE_INFRA_KUBERNETES_CLUSTER__ROLE__NAME: {{ .Values.global.cheWorkspaceClusterRole }}
{{- end }}
{{- if .Values.che.workspace.podNodeSelector }}
  CHE_WORKSPACE_POD_NODE__SELECTOR: {{ .Values.che.workspace.podNodeSelector | quote }}
{{- end }}
  CHE_CORS_ENABLED: "false"
  CHE_CORS_ALLOW__CREDENTIALS: "false"
  CHE_CORS_ALLOWED__ORIGINS: "*"
  CHE_TRACING_ENABLED: {{ .Values.global.tracingEnabled | quote }}
  JAEGER_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  JAEGER_SERVICE_NAME: "che-server"
  JAEGER_SAMPLER_MANAGER_HOST_PORT: "jaeger:5778"
  JAEGER_SAMPLER_TYPE: "const"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_MAX_QUEUE_SIZE: "10000"
  CHE_METRICS_ENABLED: {{ .Values.global.metricsEnabled | quote }}
  CHE_WORKSPACE_JAVA__OPTIONS: "-Xmx2000m"
  CHE_WORKSPACE_MAVEN__OPTIONS: "-Xmx20000m"
  CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "15"
{{- if .Values.cheServerSecureExposerJwtProxyImage }}
  CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE: {{ .Values.cheServerSecureExposerJwtProxyImage | quote }}
{{- end }}
{{- if .Values.cheWorkspacePodTolerations }}
  CHE_WORKSPACE_POD_TOLERATIONS__JSON: {{ .Values.cheWorkspacePodTolerations | toJson | quote }}
{{- end }}
