#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress
  labels:
    app: che
    component: che
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | quote }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}org/websocket-services: "che-host"
{{- if and .Values.global.tls .Values.global.tls.enabled }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "cheHost" . }}
    {{- if .Values.global.tls.secretName }}
    secretName: {{ .Values.global.tls.secretName }}
    {{- end -}}
{{- end }}
  rules:
{{- if ne .Values.global.serverStrategy "default-host" }}
  - host: {{ template "cheHost" . }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: /
        backend:
          servicePort: 8080
{{- if and (eq .Values.global.serverStrategy "single-host") (eq .Values.global.singleHostExposure "gateway") }}
          serviceName: che-gateway
{{- else }}
          serviceName: che-host
{{- end }}
