#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if and (eq .Values.global.serverStrategy "single-host") (eq .Values.global.singleHostExposure "gateway") }}

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
    component: che-gateway-config
  name: che-gateway-route-che
data:
  che.yml: |
    http:
      routers:
        che:
          rule: "PathPrefix(`/`)"
          service: che
          priority: 1
      services:
        che:
          loadBalancer:
            servers:
            - url: 'http://che-host:8080'

{{- end }}
