#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if not (contains "<" .Values.global.cheWorkspacesNamespace) }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-workspace-exec
  namespace: {{ .Values.global.cheWorkspacesNamespace }}
  labels:
    app: che
    component: che
roleRef:
  kind: Role
  name: exec
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.cheWorkspaceServiceAccount }}
  namespace: {{ .Values.global.cheWorkspacesNamespace }}
{{- end }}
