#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if not (and (eq .Values.global.serverStrategy "single-host") (eq .Values.global.singleHostExposure "gateway")) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  labels:
    app: che
    component: keycloak
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | quote }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout: "3600"
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout: "3600"
{{- if .Values.global.tls.enabled }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "true"
{{- else }}
    {{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "keycloakHost" . }}
    {{- if .Values.global.tls.secretName }}
    secretName: {{ .Values.global.tls.secretName }}
    {{- end -}}
{{- end }}
  rules:
{{- if eq .Values.global.serverStrategy "default-host" }}
  - http:
      paths:
      - path: /auth/
{{- else if eq .Values.global.serverStrategy "single-host" }}
  - host: {{ template "keycloakHost" . }}
    http:
      paths:
      - path: /auth/
{{- else }}
  - host: {{ template "keycloakHost" . }}
    http:
      paths:
      - path: /
{{- end }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: keycloak
            port:
              number: 5050

{{- end }}
