#
# Copyright (c) 2012-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if and (eq .Values.global.serverStrategy "single-host") (eq .Values.global.singleHostExposure "gateway") }}

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
    component: che-gateway-config
  name: che-gateway-route-keycloak
data:
  keycloak.yml: |
    http:
      routers:
        keycloak:
          rule: "PathPrefix(`/auth`)"
          service: keycloak
          priority: 10
      services:
        keycloak:
          loadBalancer:
            servers:
            - url: 'http://keycloak:5050'

{{- end }}
